base_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: neck0_joint
    joint_speed: 8.0
    motor:
        id: 0
        init: 2048
        min: 1
        max: 4095
base_right_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: neck1_joint
    joint_speed: 4.0
    motor:
        id: 1
        init: 1722
        min: 1331
        max: 2113
base_left_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: neck2_joint
    joint_speed: 4.0
    motor:
        id: 2
        init: 2504
        min: 2113
        max: 2895
neck_right_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: neck3_joint
    joint_speed: 4.0
    motor:
        id: 3
        init: 3026
        min: 2635
        max: 3416
neck_left_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: neck4_joint
    joint_speed: 4.0
    motor:
        id: 4
        init: 2178
        min: 1787
        max: 2568

#Pau2Motors config
pau2motors:
    topics:
        cmd_pau: neck0;neck1;neck2;neck3;neck4;Eyes_Pitch,Eye_L,Eye_R,EyeLid_U_L,EyeLid_L_L,Eyelid_U_R,EyeLid_L_R,Jaw_open,Jaw_Forward_L,Jaw_Forward_R,Lower_Lip_C,Lower_Lip_Roll_C,Lower_lip_L,Lower_Lip_Roll_L,Lower_Lip_R,Lower_Lip_Roll_R
    motors:
      Eyes_Pitch:
        binding:
          parser:
            name: property
            property: m_eyeGazeLeftPitch
          function:
            - name: linear
              min: -0.342
              max: 0.252
          hardware:
            name: pololu
            topic: right/MotorCommand
            joint_name: Eyes_Pitch
            speed: 400
            acceleration: 100
        min: -0.342
        max: 0.252
      Eye_L:
        binding:
          parser:
            name: property
            property: m_eyeGazeLeftYaw
          function:
            - name: linear
              min: -0.472
              max: 0.4
          hardware:
            name: pololu
            topic: left/MotorCommand
            joint_name: Eye_L
            speed: 400
            acceleration: 100
        min: -0.472
        max: 0.401
      Eye_R:
        binding:
          parser:
            name: property
            property: m_eyeGazeRightYaw
          function:
            - name: linear
              min: -0.356
              max: 0.342
          hardware:
            name: pololu
            topic: right/MotorCommand
            joint_name: Eye_R
            speed: 400
            acceleration: 100
        min: -0.356
        max: 0.342
      EyeLid_U_L:
        binding:
          parser:
            name: fsshapekey
            shapekey: eye-blink.UP.L
          function:
            - name: linear
              min: 0
              max: 0.6
          hardware:
            name: pololu
            topic: left/MotorCommand
            joint_name: EyeLid_U_L
            speed: 400
            acceleration: 100
        min: -0.632
        max: 0.939
      EyeLid_L_L:
        binding:
          parser:
            name: fsshapekey
            shapekey: eye-blink.LO.L
          function:
            - name: linear
              min: 0
              max: 1
          hardware:
            name: pololu
            topic: left/MotorCommand
            joint_name: EyeLid_L_L
            speed: 400
            acceleration: 100
        min: -0.842
        max: 0.729
      Eyelid_U_R:
        binding:
          parser:
            name: fsshapekey
            shapekey: eye-blink.UP.R
          function:
            - name: linear
              min: 0
              max: 0.6
          hardware:
            name: pololu
            topic: right/MotorCommand
            joint_name: Eyelid_U_R
            speed: 400
            acceleration: 100
        min: -0.87
        max: 0.701
      EyeLid_L_R:
        binding:
          parser:
            name: fsshapekey
            shapekey: eye-blink.LO.R
          function:
            - name: linear
              min: 0
              max: 1
          hardware:
            name: pololu
            topic: right/MotorCommand
            joint_name: EyeLid_L_R
            speed: 400
            acceleration: 100
        min: -0.917
        max: 0.654

    # ---Neck---

      neck0:
        binding:
          parser:
            name: getproperty
            property: m_headRotation
          function:
            - name: quaternion2euler
              axis: y
            - name: linear
              scale: 4
              translate: 0
          hardware:
            name: dynamixel
            topic: base_controller/command
        min: -3.13
        max: 3.14

      neck1:
        binding:
          parser:
            name: getproperty
            property: m_headRotation
          function:
            - name: quaternion2euler
              axis: z
            - name: linear
              scale: 2
              translate: 0
          hardware:
            name: dynamixel
            topic: base_right_controller/command
        min: -0.6
        max: 0.6

      neck2:
        binding:
          parser:
            name: getproperty
            property: m_headRotation
          function:
            - name: quaternion2euler
              axis: z
            - name: linear
              scale: -2
              translate: 0
          hardware:
            name: dynamixel
            topic: base_left_controller/command
        min: -0.6
        max: 0.6

      neck3:
        binding:
          parser:
            name: getproperty
            property: m_headRotation
          function:
            - name: quaternion2euler
              axis: z
            - name: linear
              scale: 2
              translate: 0
          hardware:
            name: dynamixel
            topic: neck_right_controller/command
        min: -0.6
        max: 0.6

      neck4:
        binding:
          parser:
            name: getproperty
            property: m_headRotation
          function:
            - name: quaternion2euler
              axis: z
            - name: linear
              scale: -2
              translate: 0
          hardware:
            name: dynamixel
            topic: neck_left_controller/command
        min: -0.6
        max: 0.6
